

spring:
  application:
    name: mail-service

logging.level.org.springframework.web: DEBUG



server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/




